name: Testing

on: 
  - push
  - pull_request

jobs:
  build:
    name: Testing (py${{ matrix.python }}-pg${{ matrix.postgres }})

    strategy:
      fail-fast: false
      matrix:
        os: 
          - "ubuntu-20.04"
        python:
          - "3.6"
          # - "3.7"
          # - "3.8"
          # - "3.9"
        postgres: # dockerhub tags
          - "9.6"
          # - "10"
          # - "11"
          # - "12"
          # - "13"

    runs-on: ${{ matrix.os }}

    env:
      PGSYSCONFDIR: .

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install pum
        run: python -m pip install .

      - name: Setup db
        shell: bash
        run: ./.ci/setup_db.sh

      - name: Run base tests
        run: nose2 -v

      - name: Run migrations tests
        shell: bash
        run: ./test/test_pum.sh
